/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RAND_H_RPCGEN
#define _RAND_H_RPCGEN

#include <rpc/rpc.h>
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>

#ifdef __cplusplus
extern "C" {
#endif


#define RAND_PROG 0x31111111
#define RAND_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define INICIALIZA_RANDOM 1
extern  void * inicializa_random_1(long *, CLIENT *);
extern  void * inicializa_random_1_svc(long *, struct svc_req *);
#define OBTIENE_SIGUIENTE_RANDOM 2
extern  double * obtiene_siguiente_random_1(void *, CLIENT *);
extern  double * obtiene_siguiente_random_1_svc(void *, struct svc_req *);
#define INICIALIZA_N1 3
extern  void * inicializa_n1_1(int *, CLIENT *);
extern  void * inicializa_n1_1_svc(int *, struct svc_req *);
#define INICIALIZA_N2 4
extern  void * inicializa_n2_1(int *, CLIENT *);
extern  void * inicializa_n2_1_svc(int *, struct svc_req *);
#define SUM 5
extern  int * sum_1(int *, CLIENT *);
extern  int * sum_1_svc(int *, struct svc_req *);
#define MUL 6
extern  int * mul_1(int *, CLIENT *);
extern  int * mul_1_svc(int *, struct svc_req *);
extern int rand_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define INICIALIZA_RANDOM 1
extern  void * inicializa_random_1();
extern  void * inicializa_random_1_svc();
#define OBTIENE_SIGUIENTE_RANDOM 2
extern  double * obtiene_siguiente_random_1();
extern  double * obtiene_siguiente_random_1_svc();
#define INICIALIZA_N1 3
extern  void * inicializa_n1_1();
extern  void * inicializa_n1_1_svc();
#define INICIALIZA_N2 4
extern  void * inicializa_n2_1();
extern  void * inicializa_n2_1_svc();
#define SUM 5
extern  int * sum_1();
extern  int * sum_1_svc();
#define MUL 6
extern  int * mul_1();
extern  int * mul_1_svc();
extern int rand_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RAND_H_RPCGEN */
