/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rand.h"

int n1 = 0;
int n2 = 0;

void *
inicializa_random_1_svc(long *argp, struct svc_req *rqstp)
{
	static char * result;
	srandom(argp);
	return (void *) &result;
}

double *
obtiene_siguiente_random_1_svc(void *argp, struct svc_req *rqstp)
{
	static double result;
	result = random();
	return &result;
}

void *
inicializa_n1_1_svc(int *argp, struct svc_req *rqstp)
{
	static char * result;
	n1 = *argp;
	return (void *) &result;
}

void *
inicializa_n2_1_svc(int *argp, struct svc_req *rqstp)
{
	static char * result;
	n2 = *argp;
	return (void *) &result;
}

int *
sum_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;
	result = n1 + n2;
	return &result;
}

int *
mul_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;
	result = n1 * n2;
	return &result;
}
