/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rand.h"


void
rand_prog_1(char *host, long semilla, int itera, int n1, int n2)
{
	
	CLIENT *clnt;

	void  *result_1;
	long  inicializa_random_1_arg = semilla = semilla;

	double  *result_2;
	char *obtiene_siguiente_random_1_arg;

	void  *result_3;
	int  inicializa_n1_1_arg = n1;

	void  *result_4;
	int  inicializa_n2_1_arg = n2;

	int  *result_5;
	int  sum_1_arg;

	int  *result_6;
	int  mul_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, RAND_PROG, RAND_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = inicializa_random_1(&inicializa_random_1_arg, clnt);
	if (result_1 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	int i = 0;
	for(i=0; i<itera; i++){
		result_2 = obtiene_siguiente_random_1((void*)&obtiene_siguiente_random_1_arg, clnt);
		if (result_2 == (double *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		printf("Siguiente random [%02d]: %d\n",(i+1),(int)*result_2);
	}

	result_3 = inicializa_n1_1(&inicializa_n1_1_arg, clnt);
	if (result_3 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = inicializa_n2_1(&inicializa_n2_1_arg, clnt);
	if (result_4 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = sum_1(&sum_1_arg, clnt);
	if (result_5 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("\n\tSuma: %d + %d = %d\n",inicializa_n1_1_arg,inicializa_n2_1_arg,*result_5);
	result_6 = mul_1(&mul_1_arg, clnt);
	if (result_6 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("\n\tMultiplicacion: %d * %d = %d\n",inicializa_n1_1_arg,inicializa_n2_1_arg,*result_6);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	int n1;
	if (argc < 5) {
		printf ("usage: %s server_host, (int)semilla, (int)iteracion, (int)n1, (int)n2\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	rand_prog_1 (host, atoi(argv[2]),atoi(argv[3]),atoi(argv[4]),atoi(argv[5]));


	exit (0);
}
